pipeline-npm.sh(1)
==================
:compat-mode!:

NAME
----
pipeline-npm.sh - a shell script

SYNOPSIS
--------

Contains all NPM related build functions


FUNCTIONS
---------

 build
 downloadAppBinary
 downloadNpmIfMissing
 executeApiCompatibilityCheck
 installNodeIfMissing
 outputFolder
 projectType
 retrieveAppName
 retrieveGroupId
 retrieveStubRunnerIds
 runE2eTests
 runSmokeTests
 testResultsAntPattern

DETAILS
-------

Script Body
~~~~~~~~~~~

Has 15 line(s). No functions are called (may set up e.g. a hook, a Zle widget bound to a key, etc.).

_Exports (environment):_ ARTIFACT_TYPE [big]*//* NODE_BIN [big]*//* NPM_BIN

build
~~~~~

____
 # npm implementation of the build function.
 # Requires [npm] and [node]. Installs those if possible
____

Has 3 line(s). Calls functions:

 

Not called by script or any function (may be e.g. a hook, a Zle widget, etc.).

downloadAppBinary
~~~~~~~~~~~~~~~~~

____
 # Just downloads the npm libraries. We will use sources
____

Has 2 line(s). Doesn't call other functions.

Not called by script or any function (may be e.g. a hook, a Zle widget, etc.).

downloadNpmIfMissing
~~~~~~~~~~~~~~~~~~~~

____
 # Downloads and installs node and npm if missing
____

Has 6 line(s). Doesn't call other functions.

Called by:

 build

executeApiCompatibilityCheck
~~~~~~~~~~~~~~~~~~~~~~~~~~~~

____
 # npm implementation of the execute API compatibility check
____

Has 2 line(s). Doesn't call other functions.

Not called by script or any function (may be e.g. a hook, a Zle widget, etc.).

installNodeIfMissing
~~~~~~~~~~~~~~~~~~~~

____
 # Installs node if missing
____

Has 7 line(s). Doesn't call other functions.

Not called by script or any function (may be e.g. a hook, a Zle widget, etc.).

_List of exports (to environment):_ LANG

outputFolder
~~~~~~~~~~~~

____
 # npm implementation of the output folder
____

Has 1 line(s). Doesn't call other functions.

Not called by script or any function (may be e.g. a hook, a Zle widget, etc.).

projectType
~~~~~~~~~~~

____
 # npm implementation of the project type
____

Has 1 line(s). Doesn't call other functions.

Not called by script or any function (may be e.g. a hook, a Zle widget, etc.).

retrieveAppName
~~~~~~~~~~~~~~~

____
 # npm implementation of the retrieve app name
____

Has 6 line(s). Doesn't call other functions.

Not called by script or any function (may be e.g. a hook, a Zle widget, etc.).

retrieveGroupId
~~~~~~~~~~~~~~~

____
 # npm implementation of the retrieve group id
____

Has 2 line(s). Doesn't call other functions.

Not called by script or any function (may be e.g. a hook, a Zle widget, etc.).

retrieveStubRunnerIds
~~~~~~~~~~~~~~~~~~~~~

____
 # npm implementation of the retrieve stub runner ids
____

Has 2 line(s). Doesn't call other functions.

Not called by script or any function (may be e.g. a hook, a Zle widget, etc.).

runE2eTests
~~~~~~~~~~~

____
 # npm implementation of the e2e tests
____

Has 2 line(s). Doesn't call other functions.

Not called by script or any function (may be e.g. a hook, a Zle widget, etc.).

runSmokeTests
~~~~~~~~~~~~~

____
 # npm implementation of the run smoke tests
____

Has 2 line(s). Doesn't call other functions.

Not called by script or any function (may be e.g. a hook, a Zle widget, etc.).

testResultsAntPattern
~~~~~~~~~~~~~~~~~~~~~

____
 # npm implementation of the test results ant pattern
____

Has 1 line(s). Doesn't call other functions.

Not called by script or any function (may be e.g. a hook, a Zle widget, etc.).

