pipeline-ansible.sh(1)
======================
:compat-mode!:

NAME
----
pipeline-ansible.sh - a shell script

SYNOPSIS
--------

Contains all Ansible related deployment functions


FUNCTIONS
---------

 __ansible_inventory
 __ansible_playbook
 completeSwitchOver
 logInToPaas
 prepareForE2eTests
 prepareForSmokeTests
 prodDeploy
 rollbackToPreviousVersion
 stageDeploy
 testDeploy
 testRollbackDeploy

DETAILS
-------

Script Body
~~~~~~~~~~~

Has 16 line(s). No functions are called (may set up e.g. a hook, a Zle widget bound to a key, etc.).

__ansible_inventory
~~~~~~~~~~~~~~~~~~~

____
 # Loads the Ansible inventory from the given [ANSIBLE_INVENTORY_DIR]. The convention is such
 # that every environment has its own file with the name of the environment. E.g. for environment
 # [test] the inventory file would be [${ANSIBLE_INVENTORY_DIR}/test].
____

Has 8 line(s). Doesn't call other functions.

Not called by script or any function (may be e.g. a hook, a Zle widget, etc.).

_Environment variables used:_ test_smoke.sh -> ENVIRONMENT

__ansible_playbook
~~~~~~~~~~~~~~~~~~

____
 # Given the presence of the Ansible inventory will first try to load a custom
 # playbook from [${ANSIBLE_CUSTOM_PLAYBOOKS_DIR}/${playbook_name}]. E.g.
 # for playbook with name [deploy-jvm-service.yml] will search by default for
 # [${__ROOT}/ansible/custom/deploy-jvm-service.yml] to apply first. If there's
 # no such file will continue applying the defaultplaybook  [${__ROOT}/ansible/deploy-jvm-service.yml]
____

Has 21 line(s). Doesn't call other functions.

Called by:

 completeSwitchOver
 prodDeploy
 rollbackToPreviousVersion
 stageDeploy
 testDeploy
 testRollbackDeploy

_Environment variables used:_ test_smoke.sh -> ENVIRONMENT

completeSwitchOver
~~~~~~~~~~~~~~~~~~

____
 # Implementation of the Ansible switch over on production
____

Has 5 line(s). Calls functions:

 completeSwitchOver
 `-- __ansible_playbook

Called by:

 prod_complete.sh/Script-Body

_Environment variables used:_ pipeline.sh -> LANGUAGE_TYPE

logInToPaas
~~~~~~~~~~~

____
 # Since there's no concept of explicit logging in in Ansible, this method does nothing
____

Has 1 line(s). Doesn't call other functions.

Not called by script or any function (may be e.g. a hook, a Zle widget, etc.).

prepareForE2eTests
~~~~~~~~~~~~~~~~~~

____
 # Ansible implementation of prepare for e2e tests
____

Has 9 line(s). Doesn't call other functions.

Uses feature(s): _export_

Called by:

 stage_e2e.sh/Script-Body

_List of exports (to environment):_ APPLICATION_URL

prepareForSmokeTests
~~~~~~~~~~~~~~~~~~~~

____
 # Ansible implementation of prepare for smoke tests
____

Has 14 line(s). Doesn't call other functions.

Uses feature(s): _export_

Called by:

 testRollbackDeploy
 test_rollback_smoke.sh/Script-Body
 test_smoke.sh/Script-Body

_List of exports (to environment):_ APPLICATION_URL [big]*//* STUBRUNNER_URL

prodDeploy
~~~~~~~~~~

____
 # Implementation of the Ansible deployment to prod
____

Has 7 line(s). Calls functions:

 prodDeploy
 `-- __ansible_playbook

Called by:

 prod_deploy.sh/Script-Body

_Environment variables used:_ pipeline.sh -> LANGUAGE_TYPE

rollbackToPreviousVersion
~~~~~~~~~~~~~~~~~~~~~~~~~

____
 # Implementation of the Ansible rolling back on production to previous version
____

Has 15 line(s). Calls functions:

 rollbackToPreviousVersion
 `-- __ansible_playbook

Called by:

 prod_rollback.sh/Script-Body

_Environment variables used:_ pipeline.sh -> LANGUAGE_TYPE

stageDeploy
~~~~~~~~~~~

____
 # Implementation of the Ansible deployment to stage
____

Has 6 line(s). Calls functions:

 stageDeploy
 `-- __ansible_playbook

Called by:

 stage_deploy.sh/Script-Body

_Environment variables used:_ pipeline.sh -> LANGUAGE_TYPE

testDeploy
~~~~~~~~~~

____
 # Implementation of the Ansible deployment to test
____

Has 15 line(s). Calls functions:

 testDeploy
 `-- __ansible_playbook

Called by:

 test_deploy.sh/Script-Body

_Environment variables used:_ pipeline.sh -> LANGUAGE_TYPE

testRollbackDeploy
~~~~~~~~~~~~~~~~~~

____
 # Implementation of the Ansible deployment to test for rollback tests
____

Has 23 line(s). Calls functions:

 testRollbackDeploy
 |-- __ansible_playbook
 `-- prepareForSmokeTests

Called by:

 test_rollback_deploy.sh/Script-Body

_Environment variables used:_ pipeline-k8s.sh -> APPLICATION_URL [big]*//* pipeline-k8s.sh -> STUBRUNNER_URL [big]*//* pipeline.sh -> LANGUAGE_TYPE [big]*//* pipeline.sh -> OUTPUT_FOLDER

