== Customizing the Project

Cloud Pipelines offers a number of ways to customize a Pipelines project:

* <<customization-overriding-scripts>>
* <<customization-overriding-pipelines>>
* <<customization-picking-features>>

[[customization-overriding-scripts]]
=== Overriding Scripts

Since Cloud Pipelines evolves, you may want to pull the most recent changes to your
Cloud Pipelines fork. To not have merge conflicts, the best approach
to extending the functionality is to use a separate script with customizations.

When we execute a script that represents a step (for example, a script named `build_and_upload.sh`),
after we source all the deployment and build-specific scripts (such as `pipeline-cf.sh`
and `projectType/pipeline-jvm.sh` with `projectType/pipeline-gradle.sh`), we set
a hook that lets you customize the behavior. If the script that we run
is `src//main/bash/build_and_upload.sh`, we search for a script in the
Cloud Pipelines repository under `src//main/bash/custom/build_and_upload.sh`,
and we source that script just before running any functions.

The following example shows such a customization:

.custom/build_and_upload.sh
====
[source,bash]
----
#!/bin/bash

function build() {
    echo "I am executing a custom build function"
}

export -f build
----
====

when the `build` function is called for our Gradle project, instead of
calling the Gradle build process, we echo the following text: `I am executing a custom build function`.
