== Customizing the Project

Cloud Pipelines offers a number of ways to customize a Pipelines project:

* <<customization-overriding-scripts>>
* <<customization-overriding-pipelines>>
* <<customization-picking-features>>

[[customization-overriding-scripts]]
=== Overriding Scripts

Since Cloud Pipelines evolves, you may want to pull the most recent changes to your
Cloud Pipelines fork. To not have merge conflicts, the best approach
to extending the functionality is to use a separate script with customizations.

When we execute a script that represents a step (for example, a script named `build_and_upload.sh`),
after we source all the deployment and build-specific scripts (such as `pipeline-cf.sh`
and `projectType/pipeline-jvm.sh` with `projectType/pipeline-gradle.sh`), we set
a hook that lets you customize the behavior. If the script that we run
is `src//main/bash/build_and_upload.sh`, we search for a script in the
Cloud Pipelines repository under `src//main/bash/custom/build_and_upload.sh`,
and we source that script just before running any functions.

The following example shows such a customization:

.custom/build_and_upload.sh
====
[source,bash]
----
#!/bin/bash

function build() {
    echo "I am executing a custom build function"
}

export -f build
----
====

when the `build` function is called for our Gradle project, instead of
calling the Gradle build process, we echo the following text: `I am executing a custom build function`.

In order to improve the extensibility, we allow fetching
of a tarball with additional files / scripts that should be applied at runtime.
That means that if you have a custom implementation of a platform that you would like
to apply, instead of maintaining your fork of Cloud Pipeline Scripts, you can
create your own repository, containing the necessary files, and produce a
tarball with those files. Then you can use `ADDITIONAL_SCRIPTS_TARBALL_URL`
`ADDITIONAL_SCRIPTS_REPO_USERNAME`, `ADDITIONAL_SCRIPTS_REPO_PASSWORD` environment
variables, to provide the URL of the tarball, together with username and password
for basic authentication if necessary (we default the credentials to `M2_SETTINGS_REPO_USERNAME:M2_SETTINGS_REPO_PASSWORD`
env vars). If the `ADDITIONAL_SCRIPTS_TARBALL_URL` is present, then we will fetch
the tarball and unpack it in the `src/main/bash` directory of Cloud Pipelines Scripts.

If you want to customize the Cloud Pipelines build, you can update the contents
of the `gradle/custom.gradle` build script. That way your customizations will not
interfere with the changes in the main part of the code, thus there should be
no merge conflicts when pulling the changes from Cloud Pipeline repositories.
