== Building the Project

This section covers how to build the project. It covers:

* <<building-project-setup>>
* <<building-prerequisites>>
* <<building-bats-submodules>>
* <<building-build-and-test>>
* <<building-generate-documentation>>
* <<building-distributions>>
* <<building-making-a-release>>

[[building-project-setup]]
=== Project Setup

In the `src/main/bash` folder, you can find all the Bash scripts that contain the pipeline logic. These
scripts are reused by both the Concourse and Jenkins pipelines.

In the `dist` folder, you can find the packaged sources of the project. Since the package
contains no tests or documentation, it is extremely small and can be used in the pipelines.

In the `docs` folder, you can find the whole generated documentation of the project.

In the `docs-source` folder, you can find the sources required to generate the documentation.

[[building-prerequisites]]
=== Prerequisites

As prerequisites, you need to have http://www.shellcheck.net/[shellcheck],
https://github.com/sstephenson/bats[bats], https://stedolan.github.io/jq/[jq]
and https://rubyinstaller.org/downloads/[ruby] installed. If you use a Linux
machine, `bats` and `shellcheck` are installed for you.

To install the required software on Linux, type the following command:

====
[source,bash]
----
$ sudo apt-get install -y ruby jq
----
====

If you use a Mac, run the following commands to install the missing software:

[source,bash]
----
$ brew install jq
$ brew install ruby
$ brew install bats
$ brew install shellcheck
----

[[building-bats-submodules]]
=== Bats Submodules

To make `bats` work properly, we needed to attach Git submodules. To have them
initialized, either clone the project or (if you have already cloned the project)
pull to update it. The following command clones the project:

====
[source,bash]
----
$ git clone --recursive https://github.com/CloudPipelines/scripts.git
----
====

The following commands pull the project:

====
[source,bash]
----
$ git submodule init
$ git submodule update
----
====

If you forget about this step, Gradle runs these steps for you.

[[building-build-and-test]]
=== Build and test

Once you have installed all the prerequisites, you can run the following command to build and test the project:

====
[source,bash]
----
$ ./gradlew clean build
----
====

[[building-generate-documentation]]
=== Generate Documentation

To generate the documentation, run the following command:

====
[source,bash]
----
$ ./gradlew generateDocs
----
====

[[building-distributions]]
=== Distributions

Cloud Pipelines has a lot of tests, including Git repositories. Those
and the documentation "`weigh`" a lot. That is why, under the `dist` folder, we
publish `zip` and `tar.gz` distributions of the sources without tests and documentation.
Whenever we release a distribution, we attach a `VERSION` file to it that contains
build and SCM information (build time, revision number, and other details). To skip the
distribution generation pass the `skipDist` property on the command line, as follows:

====
[source,bash]
----
$ ./gradlew build -PskipDist
----
====

[[building-making-a-release]]
=== Making a Release

You can run the `release` task to automatically test the project,
build the distributions, change the versions, build the docs, upload the docs to Spring Cloud Static,
tag the repo, and then revert the changed versions back to default. To do so, run the
following command:

====
[source,bash]
----
$ ./gradlew release -PnewVersion=1.0.0.RELEASE
----
====

== Releasing the Project

This section covers how to release the project by publishing a Docker image.

== CI Server Worker Prerequisites

Cloud Pipelines uses Bash scripts extensively. The following list shows the software
that needs to be installed on a CI server worker for the build to pass:

====
[source,bash]
----
 apt-get -y install \
    bash \
    git \
    tar \
    zip \
    curl \
    ruby \
    wget \
    unzip \
    python \
    jq
----
====
